services:
  - type: web
    name: educationmania
    env: python
    buildCommand: ""
    startCommand: gunicorn project.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: project.settings
